name: CI

env:
  NPM_REGISTRY_PATH: //api.backup.wadeck.ch/npm

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Configure npm registry
        run: |
          echo "@wadeck:registry=https:${NPM_REGISTRY_PATH}" >> ~/.npmrc
          echo "${NPM_REGISTRY_PATH}/:_authToken=${{ secrets.WDRIVE_NPM_TOKEN }}" >> ~/.npmrc
        env:
          NPM_REGISTRY_PATH: ${{ env.NPM_REGISTRY_PATH }}
      - run: npm ci
      - run: npm run build
      - run: npm test
